ALTER TABLE `Rolo` DROP FOREIGN KEY `Rolo_fk0`;

ALTER TABLE `Exposicao` DROP FOREIGN KEY `Exposicao_fk0`;

ALTER TABLE `Exposicao` DROP FOREIGN KEY `Exposicao_fk1`;

DROP TABLE IF EXISTS `Rolo`;

DROP TABLE IF EXISTS `Camera`;

DROP TABLE IF EXISTS `Exposicao`;

DROP TABLE IF EXISTS `Objetiva`;

